### ISSUE TITLE
Question: Is this project Okta-specific

### ISSUE THREAD

**Issue by dima767** [spring-projects/spring-security-saml-dsl#24]
Or it could be used with other SAML Identity providers like Shibboleth IDP?

**Comment by rwinch** [comment]
It is not Okta specific. However, right now it requires the user to leverage a metadata services URL or file.

**Comment by dima767** [comment]
Well, I work closely with Shibboleth IDP and any Spring technology that supports that implementation and makes our lives easier - I'm rooting for ;-)

**Comment by rwinch** [comment]
That sounds great! If you can give the DSL a try and provide feedback we can make sure it works well for your scenario.

I'm closing this, but feel free to keep additional tickets
