### ISSUE TITLE
Missing saml() method

### ISSUE THREAD

**Issue by bostone** [spring-projects/spring-security-saml-dsl#43]
Not sure what I'm missing but `org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter` does not have `saml()` method as far as I can tell so I end up with compilation error when trying to plug in this code:

```
http.authorizeRequests()
	.antMatchers("/saml/**").permitAll()
	.anyRequest().authenticated()
	.and()
	.apply(saml())
```

**Comment by mraible** [comment]
You need:

```java
import static org.springframework.security.extensions.saml2.config.SAMLConfigurer.saml;
```

**Comment by bostone** [comment]
Obviously! Thanks!
