### ISSUE TITLE
Add application screens are not matching

### ISSUE THREAD

**Issue by bostone** [spring-projects/spring-security-saml-dsl#44]
When creating the app I see screens the same way you are describing in OAUTH blog post, specifically I don't see "Configure SAML" anywhere and there's no "My Applications" link on the toolbar. Can you please comment?

**Comment by mraible** [comment]
I think you're posting this issue in the wrong project. This is Spring Security. Please close this issue and post to the repo with the example code. Thanks!

**Comment by bostone** [comment]
Your project is using Okta, right? What I'm saying that when I add application on Okta's site I don't see screens as you [describe here ](https://github.com/spring-projects/spring-security-saml-dsl/tree/master/samples/spring-security-saml-dsl-sample). Instead I see the screens you have in your other blog post that let me to setup OAuth authentication. And yes, I'm using Spring Security

**Comment by mraible** [comment]
That's fair, sorry for jumping to conclusions. I'll add this to my list of items to update.

**Comment by bostone** [comment]
I tried to type in "admin/apps/saml-wizard/create" and I got SAML wizard just now. But there's no clear way to get to it from "Add Application" button that I can see. Not sure if I'm missing a step

**Comment by mraible** [comment]
@bostone Can you post your problem and steps to reproduce on https://devforum.okta.com/? Happy to help over there and clear things up.

**Comment by bostone** [comment]
Sure, tomorrow morning. Have to call it a day (night?)

**Comment by bostone** [comment]
Ok, as promised https://devforum.okta.com/t/saml-wizard-is-hidden/692
