### ISSUE TITLE
Convert packages to spring format

### ISSUE THREAD

**Issue by jadekler** [spring-projects/spring-security-saml-dsl#6]
From @rwinch:

> If you are able, you can ensure to use group of org.springframework.security.extensions and artifact of spring-security-saml2-dsl

**Comment by jadekler** [comment]
Related: https://github.com/jadekler/spring-security-saml-dsl/issues/5

**Comment by rwinch** [comment]
Fixed via 3afa6ecb5707d89228ba4c74df9997588e2d750c
